import { Router } from 'express';
import { authMiddleware, adminMiddleware } from '../auth';
import { query } from '../db';
import {
  getPPByUserId, insertPP, deletePP,
  getDistillateKeywordsByPage, insertDistillateKeyword, deleteDistillateKeyword,
  getZlgjcByPage, deleteZlgjc, generateZlgjcKeywords,
  getKeywordMaintenanceList, insertZlgjcUrl, updateZlgjcUrl,
  clearKeywordData, getAllPlatforms,
  // 兼容 GEO 报告页面旧路径的函数
  getKeywordSearchRank, getKeywordCount, getPlatformRatio, getCoreKeywordRank,
  // 关键词生成器配置
  saveKwConfig, getKwConfig,
  // 自动生成关键词
  autoGenerateDistillateKeywords, autoGenerateBrandKeywords,
  // 手动去重
  deduplicateZlgjc,
} from '../repository';

const router = Router();

// ============ 品牌关键词 ============
router.get('/pp/list', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const userId = req.query.userId as string;
    const data = await getPPByUserId(userId);
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/pp/add', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { userId, pp } = req.body;
    const id = await insertPP(String(userId), pp);
    // 无感生成品牌关键词到zlgjc表
    try {
      const genResult = await autoGenerateBrandKeywords(String(userId), pp);
      console.log(`[Keyword] 品牌词"${pp}"自动生成品牌关键词: 新增${genResult.inserted}条, 重复${genResult.duplicated}条`);
    } catch (genErr) {
      console.error(`[Keyword] 品牌词"${pp}"自动生成失败:`, genErr);
    }
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.delete('/pp/:id', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    await deletePP(parseInt(req.params.id));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 核心关键词（distillate_keyword）============
router.get('/dstillateKeyword/getAllDstillateKeyword', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const userId = req.query.userId as string;
    const pageNum = parseInt(req.query.pageNum as string) || 1;
    const pageSize = parseInt(req.query.pageSize as string) || 9999999;
    const result = await getDistillateKeywordsByPage(userId, pageNum, pageSize);
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/dstillateKeyword/insertDstillateKeyword', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { userId, distillateKeyword } = req.body;
    const id = await insertDistillateKeyword(String(userId), distillateKeyword);
    // 无感生成蒸馏关键词到zlgjc表
    try {
      const genResult = await autoGenerateDistillateKeywords(String(userId), distillateKeyword);
      console.log(`[Keyword] 核心词"${distillateKeyword}"自动生成蒸馏关键词: 新增${genResult.inserted}条, 重复${genResult.duplicated}条`);
    } catch (genErr) {
      console.error(`[Keyword] 核心词"${distillateKeyword}"自动生成失败:`, genErr);
    }
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.get('/dstillateKeyword/deleteDstillateKeyword', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    await deleteDistillateKeyword(parseInt(req.query.id as string));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 蒸馏关键词生成 ============
router.post('/keywordsearchrank/generate', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { A, B, C, D, E, F, G, userId, keywordType } = req.body;
    const result = await generateZlgjcKeywords(String(userId), { A, B, C, D, E, F, G }, keywordType || 0);
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 关键词生成器配置 ============
router.post('/keywordsearchrank/saveKwConfig', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { userId, configType, configJson } = req.body;
    await saveKwConfig(String(userId), configType, JSON.stringify(configJson));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.get('/keywordsearchrank/getKwConfig', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const userId = req.query.userId as string;
    const configType = req.query.configType as string;
    const configJson = await getKwConfig(userId, configType);
    res.json({ code: 200, data: configJson ? JSON.parse(configJson) : null });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 蒸馏关键词库（zlgjc）============
router.get('/zlgjc/select', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const userId = req.query.userId as string;
    const pageNum = parseInt(req.query.pageNum as string) || 1;
    const pageSize = parseInt(req.query.pageSize as string) || 10;
    const keywordType = parseInt(req.query.keywordType as string) || 0;
    const result = await getZlgjcByPage(userId, pageNum, pageSize, keywordType);
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.delete('/zlgjc/delete/:id', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    await deleteZlgjc(parseInt(req.params.id));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 批量删除关键词
router.post('/zlgjc/batchDelete', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { ids } = req.body;
    if (!Array.isArray(ids) || ids.length === 0) {
      return res.json({ code: 400, message: '缺少ids参数' });
    }
    const idList = ids.map((id: any) => parseInt(id)).filter((id: number) => !isNaN(id));
    if (idList.length === 0) {
      return res.json({ code: 400, message: '无效的ids' });
    }
    const placeholders = idList.map((_: number, i: number) => `$${i + 1}`).join(',');
    await query(`DELETE FROM zlgjc WHERE id IN (${placeholders})`, idList);
    res.json({ code: 200, data: { deleted: idList.length } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 手动去重：删除同一用户同一keyword_type下value重复的关键词
router.post('/zlgjc/deduplicate', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { userId, keywordType } = req.body;
    if (!userId || keywordType === undefined) {
      return res.json({ code: 400, message: '缺少userId或keywordType参数' });
    }
    const result = await deduplicateZlgjc(String(userId), parseInt(keywordType));
    res.json({ code: 200, data: result, message: `去重完成：删除${result.deleted}条重复记录，剩余${result.remaining}条` });
  } catch (e: any) {
    res.json({ code: 500, message: '去重失败: ' + e.message });
  }
});

// 手动添加关键词
router.post('/zlgjc/add', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { userId, value, hxgjc, lxfs, keywordType } = req.body;
    if (!userId || !value) return res.json({ code: 400, message: '缺少参数' });
    await query(
      'INSERT INTO zlgjc (value, hxgjc, userid, lxfs, keyword_type) VALUES ($1, $2, $3, $4, $5)',
      [value, hxgjc || value, userId, lxfs || '', keywordType || 0]
    );
    res.json({ code: 200, message: '添加成功' });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.get('/zlgjc/platforms', async (req, res) => {
  try {
    const data = await getAllPlatforms();
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 关键词维护 ============
router.get('/zlgjc/maintenanceList', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const result = await getKeywordMaintenanceList({
      userId: req.query.userId as string,
      platform: req.query.pt as string,
      pageNum: parseInt(req.query.pageNum as string) || 1,
      pageSize: parseInt(req.query.pageSize as string) || 20,
      keyword: req.query.keyword as string,
    });
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/zlgjc/updateUrl', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { id, url, hasLxfs } = req.body;
    await updateZlgjcUrl(parseInt(id), url, hasLxfs);
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/zlgjc/insertUrl', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { zlgjcid, pt, url, hasLxfs } = req.body;
    const id = await insertZlgjcUrl({ zlgjcid: parseInt(zlgjcid), pt, url, hasLxfs });
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 数据清零 ============
router.post('/data/clear', authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { type, userId } = req.body;
    if (type === 'keyword') {
      const cleared = await clearKeywordData(userId);
      res.json({ code: 200, data: { cleared } });
    } else {
      res.json({ code: 400, message: '不支持的清零类型' });
    }
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 平台列表 ============
router.get('/pt/list', async (req, res) => {
  try {
    const data = await getAllPlatforms();
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 兼容 GEO 报告页面旧路径 ============
// 前端 dashboard 页面使用旧路径，这里提供兼容路由

// 搜索排名列表（兼容 /keywordsearchrank/keypage）
router.get('/keywordsearchrank/keypage', async (req, res) => {
  try {
    const userId = req.query.userId as string;
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const data = await getKeywordSearchRank({
      userId,
      platform: req.query.pt as string,
      keyword: req.query.keyword as string,
      type: req.query.type as string,
      page: parseInt(req.query.pageNum as string) || 1,
      pageSize: parseInt(req.query.pageSize as string) || 20,
    });

    res.json({
      code: 200,
      data: {
        list: data.list.map((item: any) => ({
          id: item.id,
          expandedKeyword: item.expanded_keyword,
          distillateKeyword: item.distillate_keyword,
          platform: item.platform,
          userId: item.user_id,
          queryTime: item.query_time,
          url: item.url,
          zlgjcUrl: item.zlgjc_url || '',
          hasLxfs: item.has_lxfs === 1,
          createTime: item.create_time,
        })),
        total: data.total,
        page: data.page,
        pageSize: data.pageSize,
      }
    });
  } catch (e) {
    console.error('[Keyword] 获取搜索排名失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 平台占比（兼容 /keywordsearchrank/platformRatio）
router.get('/keywordsearchrank/platformRatio', async (req, res) => {
  try {
    const userId = req.query.userId as string;
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const type = req.query.type as string | undefined;
    const data = await getPlatformRatio(userId, type);
    res.json({
      code: 200,
      data: data.map((item: any) => ({
        platform: item.pt,
        count: parseInt(item.count) || 0,
      }))
    });
  } catch (e) {
    console.error('[Keyword] 获取平台占比失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 核心关键词排名（兼容 /keywordsearchrank/keywordcound）
router.get('/keywordsearchrank/keywordcound', async (req, res) => {
  try {
    const userId = req.query.userId as string;
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const data = await getCoreKeywordRank(userId, 20);
    res.json({
      code: 200,
      data: data.map((item: any) => ({
        distillateKeyword: item.keyword,
        count: parseInt(item.count) || 0,
      }))
    });
  } catch (e) {
    console.error('[Keyword] 获取核心关键词排名失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 关键词数量统计（兼容 /dstillateKeyword/countDstillateKeyword）
router.get('/dstillateKeyword/countDstillateKeyword', async (req, res) => {
  try {
    const userId = req.query.userId as string;
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    // 核心关键词数（distillate_keyword 表）
    const coreResult = await query(
      'SELECT COUNT(*) as count FROM distillate_keyword WHERE user_id = $1', [userId]
    );
    const coreCount = parseInt(coreResult.rows[0].count) || 0;

    // 蒸馏关键词数（zlgjc 表）
    const zlgjcResult = await query(
      'SELECT COUNT(*) as count FROM zlgjc WHERE userid = $1', [userId]
    );
    const zlgjcCount = parseInt(zlgjcResult.rows[0].count) || 0;

    // 品牌关键词数（pp 表）
    const ppResult = await query(
      'SELECT COUNT(*) as count FROM pp WHERE user_id = $1', [userId]
    );
    const ppCount = parseInt(ppResult.rows[0].count) || 0;

    // 总收录条数（只统计已收录的）
    const totalResult = await query(
      'SELECT COUNT(*) as count FROM keyword_search_rank WHERE user_id = $1 AND query_time IS NOT NULL', [userId]
    );
    const totalCount = parseInt(totalResult.rows[0].count) || 0;

    res.json({
      code: 200,
      data: {
        count: coreCount,
        zlgjc: zlgjcCount,
        ppgjc: ppCount,
        total: totalCount,
      }
    });
  } catch (e) {
    console.error('[Keyword] 获取关键词数量失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

export default router;
