import { Router } from 'express';
import { authMiddleware, adminMiddleware } from '../auth';
import { query } from '../db';
import {
  getPPByUserId, insertPP, deletePP,
  getBrandsByUserId, insertBrand, updateBrand, deleteBrand,
  getDistillateKeywordsByPage, insertDistillateKeyword, deleteDistillateKeyword,
  getZlgjcByPage, deleteZlgjc, generateZlgjcKeywords,
  getKeywordMaintenanceList, insertZlgjcUrl, updateZlgjcUrl,
  clearKeywordData, getAllPlatforms,
  // 兼容 GEO 报告页面旧路径的函数
  getKeywordSearchRank, getKeywordCount, getPlatformRatio, getCoreKeywordRank,
  // 关键词生成器配置
  saveKwConfig, getKwConfig,
  syncDeletedDistillateWords,
  // 自动生成关键词
  autoGenerateDistillateKeywords, autoGenerateBrandKeywords,
  // 手动去重
  deduplicateZlgjc,
} from '../repository';

const router = Router();

// v2.5.36：代理数据隔离辅助函数（与 content.ts / aeo.ts 保持一致）
function getUserId(req: any): number {
  return Number(req.user?.id ?? req.user?.userId ?? 0);
}

function isAgent(req: any): boolean {
  const userLevel = String(req.user?.level ?? '');
  const userRole = String(req.user?.role ?? '');
  // v3.6：客户角色同样按代理逻辑做数据隔离
  return userLevel !== '1' && (userRole === 'agent' || userRole === 'customer');
}

/**
 * v2.5.36：解析 GEO 报告兼容路由的 userId 参数
 * - 代理强制返回自己的 userId，忽略 query 传入的 userId（防越权）
 * - 管理员/客户按原逻辑使用 query 传入的 userId
 */
function resolveGeoUserId(req: any): string | undefined {
  if (isAgent(req)) {
    return String(getUserId(req));
  }
  return req.query.userId as string | undefined;
}

// ============ 品牌关键词 ============
router.get('/pp/list', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const data = await getPPByUserId(userId, brandId);
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/pp/add', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { pp, brandId } = req.body;
    const id = await insertPP(String(userId), pp, brandId ? parseInt(brandId) : undefined);
    // 无感生成品牌关键词到zlgjc表
    try {
      const genResult = await autoGenerateBrandKeywords(String(userId), pp, brandId ? parseInt(brandId) : undefined);
      console.log(`[Keyword] 品牌词"${pp}"自动生成品牌关键词: 新增${genResult.inserted}条, 重复${genResult.duplicated}条`);
    } catch (genErr) {
      console.error(`[Keyword] 品牌词"${pp}"自动生成失败:`, genErr);
    }
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.delete('/pp/:id', authMiddleware, async (req, res) => {
  try {
    await deletePP(parseInt(req.params.id));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 品牌词（brand，v3.x 品牌词层级管理）============
// 品牌词下辖：核心关键词(distillate_keyword)、蒸馏关键词(zlgjc)、品牌关键词(pp)
router.get('/brands', authMiddleware, async (req, res) => {
  try {
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const list = await getBrandsByUserId(userId);
    res.json({ code: 200, data: list });
  } catch (e: any) {
    res.json({ code: 500, message: e.message });
  }
});

router.post('/brands', authMiddleware, async (req, res) => {
  try {
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { name } = req.body;
    if (!name || !String(name).trim()) {
      return res.json({ code: 400, message: '品牌词名称必填' });
    }
    const id = await insertBrand(String(userId), String(name).trim());
    res.json({ code: 200, data: { id } });
  } catch (e: any) {
    res.json({ code: 500, message: e.message });
  }
});

router.put('/brands/:id', authMiddleware, async (req, res) => {
  try {
    const { name, is_active } = req.body;
    await updateBrand(parseInt(req.params.id), name, is_active === undefined ? undefined : !!is_active);
    res.json({ code: 200 });
  } catch (e: any) {
    res.json({ code: 500, message: e.message });
  }
});

router.delete('/brands/:id', authMiddleware, async (req, res) => {
  try {
    await deleteBrand(parseInt(req.params.id));
    res.json({ code: 200 });
  } catch (e: any) {
    res.json({ code: 500, message: e.message });
  }
});

// ============ 核心关键词（distillate_keyword）============
router.get('/dstillateKeyword/getAllDstillateKeyword', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const pageNum = parseInt(req.query.pageNum as string) || 1;
    const pageSize = parseInt(req.query.pageSize as string) || 9999999;
    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const result = await getDistillateKeywordsByPage(userId, pageNum, pageSize, brandId);
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/dstillateKeyword/insertDstillateKeyword', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { distillateKeyword, brandId } = req.body;
    const id = await insertDistillateKeyword(String(userId), distillateKeyword, brandId ? parseInt(brandId) : undefined);
    // 无感生成蒸馏关键词到zlgjc表
    try {
      const genResult = await autoGenerateDistillateKeywords(String(userId), distillateKeyword, brandId ? parseInt(brandId) : undefined);
      console.log(`[Keyword] 核心词"${distillateKeyword}"自动生成蒸馏关键词: 新增${genResult.inserted}条, 重复${genResult.duplicated}条`);
    } catch (genErr) {
      console.error(`[Keyword] 核心词"${distillateKeyword}"自动生成失败:`, genErr);
    }
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.get('/dstillateKeyword/deleteDstillateKeyword', authMiddleware, async (req, res) => {
  try {
    await deleteDistillateKeyword(parseInt(req.query.id as string));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 蒸馏关键词生成 ============
router.post('/keywordsearchrank/generate', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { A, B, C, D, E, F, G, keywordType } = req.body;
    // v3.16.x：生成前先同步删除词库里使用已删除词汇的关键词
    //   用户删除了生成器某环节词汇（如D同义词删掉"工厂"）后直接点生成，词库同步清理
    const syncConfigType = (keywordType || 0) === 1 ? 'brand' : 'distillate';
    const syncResult = await syncDeletedDistillateWords(String(userId), syncConfigType, JSON.stringify({ A, B, C, D, E, F }));
    if (syncResult.deleted > 0) {
      console.log(`[Generate] 同步删除词库关键词 ${syncResult.deleted} 条:`, JSON.stringify(syncResult.groups));
    }
    const result = await generateZlgjcKeywords(String(userId), { A, B, C, D, E, F, G }, keywordType || 0);
    res.json({ code: 200, data: { ...result, syncedDeleted: syncResult } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 关键词生成器配置 ============
router.post('/keywordsearchrank/saveKwConfig', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { configType, configJson } = req.body;
    console.log('[saveKwConfig] 收到保存请求:', { userId, configType, configJsonKeys: configJson ? Object.keys(configJson) : null });
    // v3.16.x：先同步删除词库里使用已删除词汇的关键词（对比新旧配置）
    //   用户删除了某环节词汇（如D同义词删掉"工厂"），词库里用到这些词的关键词同步删除
    const syncResult = await syncDeletedDistillateWords(String(userId), configType, JSON.stringify(configJson));
    if (syncResult.deleted > 0) {
      console.log(`[saveKwConfig] 同步删除词库关键词 ${syncResult.deleted} 条:`, JSON.stringify(syncResult.groups));
    }
    await saveKwConfig(String(userId), configType, JSON.stringify(configJson));
    console.log('[saveKwConfig] 保存成功, userId:', userId, 'configType:', configType, '同步删除:', syncResult.deleted);
    res.json({ code: 200, data: { syncedDeleted: syncResult } });
  } catch (e: any) {
    console.error('[saveKwConfig] 保存失败:', e.message);
    res.json({ code: 500, message: '服务器错误: ' + e.message });
  }
});

router.get('/keywordsearchrank/getKwConfig', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const configType = req.query.configType as string;
    console.log('[getKwConfig] 收到查询请求:', { userId, configType });
    const configJson = await getKwConfig(userId, configType);
    console.log('[getKwConfig] 查询结果:', { userId, configType, found: !!configJson, preview: configJson ? configJson.substring(0, 100) : null });
    res.json({ code: 200, data: configJson ? JSON.parse(configJson) : null });
  } catch (e: any) {
    console.error('[getKwConfig] 查询失败:', e.message);
    res.json({ code: 500, message: '服务器错误: ' + e.message });
  }
});

// 诊断端点（临时，排查词汇配置问题用，不需要认证，方便浏览器直接访问）
router.get('/keywordsearchrank/debugKwConfig', async (req, res) => {
  try {
    const result = await query('SELECT id, user_id, config_type, length(config_json) as json_len, substring(config_json, 1, 200) as json_preview, update_time FROM kw_config ORDER BY id');
    res.json({ code: 200, data: result.rows, count: result.rows.length });
  } catch (e: any) {
    res.json({ code: 500, message: e.message });
  }
});

// ============ 蒸馏关键词库（zlgjc）============
router.get('/zlgjc/select', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const pageNum = parseInt(req.query.pageNum as string) || 1;
    const pageSize = parseInt(req.query.pageSize as string) || 10;
    const keywordType = parseInt(req.query.keywordType as string) || 0;
    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const result = await getZlgjcByPage(userId, pageNum, pageSize, keywordType, brandId);
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.delete('/zlgjc/delete/:id', authMiddleware, async (req, res) => {
  try {
    await deleteZlgjc(parseInt(req.params.id));
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 批量删除关键词
router.post('/zlgjc/batchDelete', authMiddleware, async (req, res) => {
  try {
    const { ids } = req.body;
    if (!Array.isArray(ids) || ids.length === 0) {
      return res.json({ code: 400, message: '缺少ids参数' });
    }
    const idList = ids.map((id: any) => parseInt(id)).filter((id: number) => !isNaN(id));
    if (idList.length === 0) {
      return res.json({ code: 400, message: '无效的ids' });
    }
    const placeholders = idList.map((_: number, i: number) => `$${i + 1}`).join(',');
    await query(`DELETE FROM zlgjc WHERE id IN (${placeholders})`, idList);
    res.json({ code: 200, data: { deleted: idList.length } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 手动去重：删除同一用户同一keyword_type下value重复的关键词
router.post('/zlgjc/deduplicate', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { keywordType } = req.body;
    if (!userId || keywordType === undefined) {
      return res.json({ code: 400, message: '缺少userId或keywordType参数' });
    }
    const result = await deduplicateZlgjc(String(userId), parseInt(keywordType));
    res.json({ code: 200, data: result, message: `去重完成：删除${result.deleted}条重复记录，剩余${result.remaining}条` });
  } catch (e: any) {
    res.json({ code: 500, message: '去重失败: ' + e.message });
  }
});

// 手动添加关键词
router.post('/zlgjc/add', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { value, hxgjc, lxfs, keywordType, brandId } = req.body;
    if (!userId || !value) return res.json({ code: 400, message: '缺少参数' });
    // ON CONFLICT 去重：如果 (userid, value, keyword_type) 已存在则不插入
    await query(
      brandId
        ? `INSERT INTO zlgjc (value, hxgjc, userid, lxfs, keyword_type, brand_id)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (userid, value, keyword_type) DO NOTHING`
        : `INSERT INTO zlgjc (value, hxgjc, userid, lxfs, keyword_type)
           VALUES ($1, $2, $3, $4, $5)
           ON CONFLICT (userid, value, keyword_type) DO NOTHING`,
      brandId
        ? [value, hxgjc || value, userId, lxfs || '', keywordType || 0, parseInt(brandId)]
        : [value, hxgjc || value, userId, lxfs || '', keywordType || 0]
    );
    res.json({ code: 200, message: '添加成功' });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.get('/zlgjc/platforms', async (req, res) => {
  try {
    const data = await getAllPlatforms();
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 关键词维护 ============
router.get('/zlgjc/maintenanceList', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : (req.query.userId as string);
    const result = await getKeywordMaintenanceList({
      userId,
      platform: req.query.pt as string,
      pageNum: parseInt(req.query.pageNum as string) || 1,
      pageSize: parseInt(req.query.pageSize as string) || 20,
      keyword: req.query.keyword as string,
    });
    res.json({ code: 200, data: result });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/zlgjc/updateUrl', authMiddleware, async (req, res) => {
  try {
    const { id, url, hasLxfs } = req.body;
    await updateZlgjcUrl(parseInt(id), url, hasLxfs);
    res.json({ code: 200 });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

router.post('/zlgjc/insertUrl', authMiddleware, async (req, res) => {
  try {
    const { zlgjcid, pt, url, hasLxfs } = req.body;
    const id = await insertZlgjcUrl({ zlgjcid: parseInt(zlgjcid), pt, url, hasLxfs });
    res.json({ code: 200, data: { id } });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 数据清零 ============
router.post('/data/clear', authMiddleware, async (req, res) => {
  try {
    // v2.5.36：代理强制用自己 userId
    const userId = isAgent(req) ? String(getUserId(req)) : req.body.userId;
    const { type } = req.body;
    if (type === 'keyword') {
      const cleared = await clearKeywordData(userId);
      res.json({ code: 200, data: { cleared } });
    } else {
      res.json({ code: 400, message: '不支持的清零类型' });
    }
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 平台列表 ============
router.get('/pt/list', async (req, res) => {
  try {
    const data = await getAllPlatforms();
    res.json({ code: 200, data });
  } catch (e) {
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 兼容 GEO 报告页面旧路径 ============
// 前端 dashboard 页面使用旧路径，这里提供兼容路由
// v2.5.36：所有兼容路由加 authMiddleware + isAgent 数据隔离

// 搜索排名列表（兼容 /keywordsearchrank/keypage）
router.get('/keywordsearchrank/keypage', authMiddleware, async (req, res) => {
  try {
    const userId = resolveGeoUserId(req);
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const data = await getKeywordSearchRank({
      userId,
      platform: req.query.pt as string,
      keyword: req.query.keyword as string,
      type: req.query.type as string,
      brandId: req.query.brandId ? parseInt(req.query.brandId as string) : undefined,
      page: parseInt(req.query.pageNum as string) || 1,
      pageSize: parseInt(req.query.pageSize as string) || 20,
    });

    res.json({
      code: 200,
      data: {
        list: data.list.map((item: any) => ({
          id: item.id,
          expandedKeyword: item.expanded_keyword,
          distillateKeyword: item.distillate_keyword,
          platform: item.platform,
          userId: item.user_id,
          queryTime: item.query_time,
          url: item.url,
          zlgjcUrl: item.source === 'real'
            ? (item.zlgjc_url || (item.id ? `/api/real-collect/results/${item.id}/page` : ''))
            : (item.zlgjc_url || ''),
          hasLxfs: item.has_lxfs === 1,
          createTime: item.create_time,
        })),
        total: data.total,
        page: data.page,
        pageSize: data.pageSize,
      }
    });
  } catch (e) {
    console.error('[Keyword] 获取搜索排名失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 平台占比（兼容 /keywordsearchrank/platformRatio）
router.get('/keywordsearchrank/platformRatio', authMiddleware, async (req, res) => {
  try {
    const userId = resolveGeoUserId(req);
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const type = req.query.type as string | undefined;
    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const data = await getPlatformRatio(userId, type, brandId);
    res.json({
      code: 200,
      data: data.map((item: any) => ({
        platform: item.pt,
        count: parseInt(item.count) || 0,
      }))
    });
  } catch (e) {
    console.error('[Keyword] 获取平台占比失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 核心关键词排名（兼容 /keywordsearchrank/keywordcound）
router.get('/keywordsearchrank/keywordcound', authMiddleware, async (req, res) => {
  try {
    const userId = resolveGeoUserId(req);
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const data = await getCoreKeywordRank(userId, 20, brandId);
    res.json({
      code: 200,
      data: data.map((item: any) => ({
        distillateKeyword: item.keyword,
        count: parseInt(item.count) || 0,
      }))
    });
  } catch (e) {
    console.error('[Keyword] 获取核心关键词排名失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// 关键词数量统计（兼容 /dstillateKeyword/countDstillateKeyword）
router.get('/dstillateKeyword/countDstillateKeyword', authMiddleware, async (req, res) => {
  try {
    const userId = resolveGeoUserId(req);
    if (!userId) return res.json({ code: 400, message: '缺少userId' });

    const brandId = req.query.brandId ? parseInt(req.query.brandId as string) : undefined;
    const brandCoreFilter = brandId ? ' AND brand_id = ' + brandId : '';
    const brandZlgjcFilter = brandId ? ' AND brand_id = ' + brandId : '';
    const brandPpFilter = brandId ? ' AND brand_id = ' + brandId : '';

    // 核心关键词数（distillate_keyword 表）
    const coreResult = await query(
      'SELECT COUNT(*) as count FROM distillate_keyword WHERE user_id = $1' + brandCoreFilter, [userId]
    );
    const coreCount = parseInt(coreResult.rows[0].count) || 0;

    // 蒸馏关键词数（zlgjc 表）
    const zlgjcResult = await query(
      'SELECT COUNT(*) as count FROM zlgjc WHERE userid = $1' + brandZlgjcFilter, [userId]
    );
    const zlgjcCount = parseInt(zlgjcResult.rows[0].count) || 0;

    // 品牌关键词数（pp 表）
    const ppResult = await query(
      'SELECT COUNT(*) as count FROM pp WHERE user_id = $1' + brandPpFilter, [userId]
    );
    const ppCount = parseInt(ppResult.rows[0].count) || 0;

    // 总收录条数（只统计已收录的，按品牌词过滤）
    const totalResult = await query(
      'SELECT COUNT(*) as count FROM keyword_search_rank k WHERE k.user_id = $1 AND k.query_time IS NOT NULL' +
      (brandId ? ` AND EXISTS (SELECT 1 FROM zlgjc zb WHERE zb.value = k.distillate_keyword AND zb.userid = k.user_id AND zb.brand_id = ${brandId})` : ''),
      [userId]
    );
    const totalCount = parseInt(totalResult.rows[0].count) || 0;

    res.json({
      code: 200,
      data: {
        count: coreCount,
        zlgjc: zlgjcCount,
        ppgjc: ppCount,
        total: totalCount,
      }
    });
  } catch (e) {
    console.error('[Keyword] 获取关键词数量失败:', e);
    res.json({ code: 500, message: '服务器错误' });
  }
});

// ============ 临时诊断接口（v3.8.17：排查核心关键词显示错误问题）============
// 用法：GET /api/keyword/debug/core-keywords?userId=xxx
// 返回：distillate_keyword 表数据 + zlgjc.hxgjc 字段数据 + 诊断信息
// 这个接口仅用于排查问题，不影响正常业务逻辑
router.get('/debug/core-keywords', authMiddleware, async (req, res) => {
  try {
    const queryUserId = req.query.userId as string;
    const result: any = {
      queryUserId,
      serverTime: new Date().toISOString(),
    };

    // 1. 查询 distillate_keyword 表的所有 user_id（前20个）
    const allUsersResult = await query(
      `SELECT DISTINCT user_id, COUNT(*) as cnt FROM distillate_keyword GROUP BY user_id ORDER BY user_id LIMIT 20`
    );
    result.allUserIdsInDistillateTable = allUsersResult.rows.map((r: any) => ({
      userId: r.user_id,
      count: parseInt(r.cnt),
    }));

    // 2. 如果传了 userId，查询该 userId 的核心关键词
    if (queryUserId) {
      const userKeywordsResult = await query(
        `SELECT id, distillate_keyword, user_id, zt, create_time FROM distillate_keyword WHERE user_id = $1 ORDER BY id`,
        [queryUserId]
      );
      result.distillateKeywordForUser = userKeywordsResult.rows.map((r: any) => ({
        id: r.id,
        keyword: r.distillate_keyword,
        userId: r.user_id,
        zt: r.zt,
        createTime: r.create_time,
      }));

      // 3. 查询 zlgjc 表中该 userid 的 hxgjc 字段（前20个）
      const zlgjcHxgjcResult = await query(
        `SELECT DISTINCT hxgjc, COUNT(*) as cnt FROM zlgjc WHERE userid = $1 AND hxgjc IS NOT NULL AND hxgjc != '' GROUP BY hxgjc ORDER BY cnt DESC LIMIT 20`,
        [queryUserId]
      );
      result.zlgjcHxgjcForUser = zlgjcHxgjcResult.rows.map((r: any) => ({
        hxgjc: r.hxgjc,
        count: parseInt(r.cnt),
      }));

      // 4. 查询 zlgjc 表中该 userid 的蒸馏词样本（前10个）
      const zlgjcSampleResult = await query(
        `SELECT id, value, hxgjc, keyword_type FROM zlgjc WHERE userid = $1 AND (keyword_type = 0 OR keyword_type IS NULL) ORDER BY id LIMIT 10`,
        [queryUserId]
      );
      result.zlgjcSampleForUser = zlgjcSampleResult.rows.map((r: any) => ({
        id: r.id,
        value: r.value,
        hxgjc: r.hxgjc,
        keywordType: r.keyword_type,
      }));
    }

    res.json({ code: 200, data: result });
  } catch (e: any) {
    console.error('[debug/core-keywords] 查询失败:', e);
    res.json({ code: 500, message: '服务器错误: ' + e.message });
  }
});

export default router;
